### ISSUE TITLE
[Bug Report]: PRODUCT - FW VERSION - HUB

### ISSUE THREAD

**Issue by WPJBressette** [InovelliUSA/Firmware#11]
### What product is the bug report for?

Blue Series 2-1 Switch (VZM31-SN)

### FW Version

2.18

### Hub

HA Yellow

### Bug Report Details

New switch from aartech.ca switch arrived with 2.18 firmware installed

### How To Reproduce

order switch from aartech and it has 2.18 firmware installed

**Comment by InovelliUSA** [comment]
I think your concern is that the fw file is in the Beta directory? I have moved it over to the production directory.
